AuthToken="xxxxx"
Address="127.0.0.1:8881"
HarborAddress="harbor.xxxxx.com/library"

[TelegramConfig]
BoltDBPath="bolt.db"
BotToken="7391631700:xxxxxxxx"
UserRegisterToken="QJqrW4Vg"

[LoggerConfig]
Filename="harbor.log"
MaxSize=25 # 25MB

[AdminAuth]
Token="xxxxxxx"

[PostgresConfig]
Host="127.0.0.1"
Port=5432
User="root"
Password="root"
DBName="cicd"

